server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
logging:
  level:
    ROOT: INFO
